input<-readline(prompt="Enter numbers seperated by spaces")
numbers<-as.numeric(unlist(strsplit(input," ")))
print(numbers)
cat("maximum of the array:",max(numbers))
cat("minimum of the array",min(numbers))
cat("Average of the array",mean(numbers))
cat("sum:",sum(numbers))
cat("square root values",sqrt(numbers))
cat("rounded values:",round(numbers))